### ISSUE TITLE
chefもstretcherでやらせたい

### ISSUE THREAD

**Issue by tjinjin** [tjinjin/try-stretcher#10]
いまだとnodeファイルを作成してcookするという作業がある。そこを何とかしたい。またServerspecもやりたい。

**Comment by tjinjin** [comment]
実現するまでに考えられる道のり
- ローカルに対しchefを実行するにはknife soloは内部的にchef-solo使っている。

```
sudo chef-solo -c solo.rb -j dna.json
```

コンパイル？みたいなことをやってtarball化、stretcherでchef-soloすれば良さそう

**Comment by tjinjin** [comment]
tarball化するに当たって、capistranoかrakeなのかわからないけど何らかのツールでtarball化・S3へのアップロード・manifestの作成・S3へのアップロードを考える必要がありそう

**Comment by tjinjin** [comment]
ノードのIPの情報とかは設定ファイルに持たせたくない。やるとしても動的に設定したい。consul-templateとかでnodeファイルとか作れる？

**Comment by tjinjin** [comment]
awsのmetadata使えばローカルIP取れる。それを使えるようにすればいいかも

**Comment by tjinjin** [comment]
solo.rbにgenerateとかもろもろ考えるとprepare済みのAMIを作って置いて、buildサーバにローカルから`knife solo`した後にそれを固める方が楽かも

**Comment by tjinjin** [comment]
solo.rbのサンプル

``` ruby
base = File.expand_path('..', __FILE__)

nodes_path                File.join(base, 'nodes')
role_path                 File.join(base, 'roles')
data_bag_path             File.join(base, 'data_bags')
encrypted_data_bag_secret File.join(base, 'data_bag_key')
environment_path          File.join(base, 'environments')
environment               "_default"
ssl_verify_mode           :verify_peer

cookbook_path []
cookbook_path << File.join(base, 'cookbooks-1') 
cookbook_path << File.join(base, 'cookbooks-2') 
cookbook_path << File.join(base, 'cookbooks-3') 
```

**Comment by tjinjin** [comment]
solo.rbを作成してカレントでtgzを作った。それをscpでサーバに送る。

``` ruby
base = File.expand_path('..', __FILE__)

nodes_path                File.join(base, 'nodes')
role_path                 File.join(base, 'roles')
data_bag_path             File.join(base, 'data_bags')
encrypted_data_bag_secret File.join(base, 'data_bag_key')
environment_path          File.join(base, 'environments')
environment               "development"
ssl_verify_mode           :verify_peer

cookbook_path []
cookbook_path << File.join(base, 'cookbooks')
cookbook_path << File.join(base, 'site-cookbooks')
```

``` sh
$ tar zcf chef.tgz --exclude aws .
```

**Comment by tjinjin** [comment]
サーバ側で適当なディレクトリで解凍しchef-solo実行できた

``` sh
$ sudo chef-solo -c solo.rb -j nodes/192.168.34.42.json
```

**Comment by tjinjin** [comment]
```
$ consul watch -type event -name chef stretcher
```

で待機

manifestを作成

``` yml
src: file:///home/vagrant/chef.tgz
checksum: 35dc42d23d8d18c3ab86f03d18ab16f0
dest: /home/vagrant/releases
commands:
  pre:
    - echo 'staring deploy'
  post:
    - sudo chef-solo -c /home/vagrant/releases/solo.rb -j /home/vagrant/releases/nodes/192.168.34.42.json
  success:
    - echo 'deploy success'
  failure:
    - echo 'deploy failed!!'
excludes:
  - "*.pid"
  - "*.socket"
```

でevent発行したら動いた！

```
$ consul event -name "chef" "file:///home/vagrant/chef.yml"
```
